### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by ismaelga** [ismaelga/react-json-editor#1]
- [ ] Option to parse false as null on boolean. [WIP]
- [x] Provide props to SectionWrapper for array manipulation. [WIP]
- [ ] Avoid usign `for(.. in ..) {}` because of IE
- [ ] Support arrays at top-level or give a nice error message in case of wrong usage.
- [ ] Throw error on invalid type
- [ ] Ensure string type as default everywhere.
- [ ] Improve demo page 💄
- [ ] Add a CONTRIBUTING.md file as a guide to help possible contributors

**Comment by bananafunctor** [comment]
Any plans on updating the npm package soon :)  ?

**Comment by ismaelga** [comment]
I want to at least have "Option to parse false as null on boolean." before releasing, for backward compatibility.

**Comment by barrymichaeldoyle** [comment]
Are you still working on this project?

**Comment by ismaelga** [comment]
@barrymichaeldoyle not really. 😞I'm not using it on any project atm. And since I've started worked on this project https://github.com/mozilla-services/react-jsonschema-form appeared, which I think is better designed.

I might some day try to fix some of the recurring issues people are having with react-json-editor. It's been hard to arrange free time for doing it. Sorry

**Comment by barrymichaeldoyle** [comment]
All good man, thanks for the heads up 👍 I know we all get busy with other things, happens with me too :)
